version: '3.8'

services:  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: test-sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "TestDB"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts/sqlserver:/docker-entrypoint-initdb.d
    command: /bin/bash /docker-entrypoint-initdb.d/entrypoint.sh
    restart: unless-stopped

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpass"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: test-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "adminpass"
      MONGO_INITDB_DATABASE: "testdb"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts/mongodb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: test-redis
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Cassandra
  cassandra:
    image: cassandra:4.0
    container_name: test-cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-scripts/cassandra:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sqlserver_data:
  mysql_data:
  postgres_data:
  mongodb_data:
  redis_data:
  cassandra_data:
